### PR TITLE
Redesign docs [Do not merge]

### PR DESCRIPTION
**Pull request by timuric**

### CODE REVIEW

**Review by 2can — APPROVED** [review]

**Review by mmiszy — APPROVED** [review]

**Comment by patrys** [comment]
Dark mode seems broken

image

**Comment by timuric** [comment]
> Dark mode seems broken
> 
> image

@patrys deliberately left like that, we are going to drop card overview screens as they are not useful and create inconsistent navigation patterns. This PR needs structural changes before merging

**Comment by patrys** [comment]
@timuric 

>deliberately left like that

Why are only index pages broken though?

**Review by zaiste — APPROVED** [review]

**Comment by timuric** [comment]
> @timuric
> 
> > deliberately left like that
> 
> Why are only index pages broken though?

Index pages don't have swizzled footer component, which is used to hook into theme events. Global theme would be moved to search component as it is present on all screens and would be more reliable.

**Comment by patrys** [comment]
@timuric I don't understand why we're using custom components with React hooks to theme the page. Docusaurus supports theming without any special hacks.

**Pull request closed without merging**
