### PR TITLE
Upgrade Docusaurus, GraphQL-Markdown

### PR DESCRIPTION
**Pull request by patrys**
New API reference, 100% more glamour

### CODE REVIEW

**Review by peelar — APPROVED** [review]

**Review by krzysztofwolski — APPROVED** [review]

**Comment by peelar** [comment]
@patrys some docs got out of date. Once conflicts are resolved, we can merge.

**Comment by patrys** [comment]
@peelar I won't have time to do it today so if you have a minute, it should be a matter of rerunning the reference generator.

**Comment by krzysztofwolski** [comment]
Docosaurus 2.2.0 added mermaid support. Why should we care? 
Currently:
image
After update:
image

🎉  visible mermaid diagrams in dark mode 🎉 

PR in a minute, I'm checking if it builds ATM

**Comment by patrys** [comment]
@krzysztofwolski Could you also rerun the reference generator so we can merge this?

**Comment by krzysztofwolski** [comment]
@patrys Done :) Waiting for the CI

**Pull request merged**
